default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [--verbose, --force-scope, feat, fix, refactor, test, docs, build, ops, chore]

  - repo: https://github.com/cisagov/pre-commit-packer
    rev: v0.3.0
    hooks:
      - id: packer_validate
        files: ^infra/packer/.*\.hcl$
      - id: packer_fmt
        files: ^infra/packer/.*\.hcl$

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: ^scripts/.*\.sh$

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.3
    hooks:
      - id: terraform_fmt
        files: ^infra/terraform/.*\.tf$
      - id: terraform_validate
        files: ^infra/terraform/.*\.tf$
      # - id: terraform_docs
      #   files: ^infra/terraform/.*\.tf$
      - id: terraform_tflint
        files: ^infra/terraform/.*\.tf$
      - id: terraform_trivy
        files: ^infra/terraform/.*\.tf$
