---
# tasks file for chezmoi

- name: Include install tasks
  ansible.builtin.include_tasks: install.yml
  when: chezmoi_state == "present"

- name: Include cleanup tasks
  ansible.builtin.include_tasks: cleanup.yml
  when: chezmoi_state == "absent"
