---
# tasks file for chezmoi
- name: Ensure chezmoi_user is defined
  ansible.builtin.assert:
    that:
      - chezmoi_user is defined
    fail_msg: "chezmoi_user is not defined"

- name: Ensure chezmoi_profile is defined
  ansible.builtin.assert:
    that:
      - chezmoi_profile is defined
    fail_msg: "chezmoi_profile is not defined"

- name: Ensure chezmoi source directory .local/share/chezmoi exists for user {{ chezmoi_user }}
  ansible.builtin.file:
    path: "/home/{{ chezmoi_user }}/.local/share/chezmoi"
    state: directory
    owner: "{{ chezmoi_user }}"
    group: "{{ chezmoi_user }}"
    mode: "0755"
  become: true
  become_user: "{{ chezmoi_user }}"

- name: Ensure .chezmoidata.yaml file exists in users's chezmoi source directory
  ansible.builtin.file:
    path: "/home/{{ chezmoi_user }}/.local/share/chezmoi/.chezmoidata.yaml"
    state: touch
    owner: "{{ chezmoi_user }}"
    group: "{{ chezmoi_user }}"
    mode: "0644"
  become: true
  become_user: "{{ chezmoi_user }}"

- name: Update .chezmoidata.yaml file with chezmoi_profile
  ansible.builtin.lineinfile:
    path: "/home/{{ chezmoi_user }}/.local/share/chezmoi/.chezmoidata.yaml"
    line: "profile: {{ chezmoi_profile }}"
    state: present
    owner: "{{ chezmoi_user }}"
    group: "{{ chezmoi_user }}"
    mode: "0644"
  become: true
  become_user: "{{ chezmoi_user }}"

- name: Ensure .local/bin directory exists for user {{ chezmoi_user }}
  ansible.builtin.file:
    path: "/home/{{ chezmoi_user }}/.local/bin"
    state: directory
    owner: "{{ chezmoi_user }}"
    group: "{{ chezmoi_user }}"
    mode: "0755"
  become: true
  become_user: "{{ chezmoi_user }}"

- name: Download and install chezmoi
  ansible.builtin.shell: 'sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /home/{{ chezmoi_user }}/.local/bin'
  args:
    creates: "/home/{{ chezmoi_user }}/.local/bin/chezmoi"
  become: true
  become_user: "{{ chezmoi_user }}"

- name: Initialize dotfiles with chezmoi
  ansible.builtin.command: "/home/{{ chezmoi_user }}/.local/bin/chezmoi init --apply {{ chezmoi_github_username }}"
  args:
    creates: "/home/{{ chezmoi_user }}/.local/share/chezmoi"
  become: true
  become_user: "{{ chezmoi_user }}"
  when: chezmoi_github_username is defined
