---
# Group variables for all hosts
ansible_user: ansible
ansible_become_method: sudo
ansible_become_user: root
ansible_ssh_private_key_file: ~/.ssh/ansible/id_ed25519
ansible_python_interpreter: /usr/bin/python3

# packages to be installed on all hosts
common_apt_packages:
  - vim
  - git
  - curl
  - wget
  - htop
  - tree
