all:
  children:
    supermicro:
      hosts:
        dl14:
          ansible_host: 192.168.114.36  # Replace with actual IP
        dl15:
          ansible_host: 192.168.114.35  # Replace with actual IP

    rpi:
      hosts:
        rpi-node1:
          ansible_host: 192.168.114.31  # Replace with actual IP
        rpi-node2:
          ansible_host: 192.168.114.32  # Replace with actual IP
        rpi-node3:
          ansible_host: 192.168.114.33  # Replace with actual IP
        rpi-node4:
          ansible_host: 192.168.114.34  # Replace with actual IP

    dietpi:
      children:
        rpi:

    kvm_hosts:
      children:
        supermicro:
